### ISSUE TITLE
Measuring Pauli in N(S) Throws Exception

### ISSUE THREAD

**Issue by bcriger** [Krastanov/QuantumClifford.jl#31]
I've noticed that, when trying to measure an operator which is in the logical group of a `MixedDestabilizer`, a `BoundsError` is thrown. I've tried to run the following minimal example:

    using QuantumClifford
    using QuantumClifford.Experimental.NoisyCircuits
    using Test
    
    state = Register(MixedDestabilizer(S"ZZ"), zeros(Bool, 1))
    meas = DenseMeasurement(P"ZI", 1)

    @test_throws nothing state, flag = applyop!(state, meas)

The result I see is:

    Test Failed at REPL[98]:1
      Expression: (state, flag) = applyop!(state, op)
        Expected: nothing
          Thrown: BoundsError(UInt8[0x00, 0x00], (0,))
    ERROR: There was an error during testing

I think that this is happening because this case involves a random measurement result, without the measured operator anticommuting with a stabilizer. 

Taking a look around the codebase, I've noticed a few things. First, the `BoundsError` is coming from either line 436 or 438 of `NoisyCircuits.jl`, which attempts to set `stabilizerview(stab).phases[anticom]`, where `stab` and `anticom` come from `stab,anticom,r = project!(stab, op.pauli)` on line 433. 
In `project!(d::MixedDestabilizer,pauli::PauliOperator;keep_result::Bool=true,phases::Bool=true)` (beginning line 356, `project_trace_reset.jl`), there's some logic to determine the index of the stabilizer that `pauli` anticommutes with. There's a separate variable called `anticomlog` which gets set to `j` if `pauli` anticommutes with logical `j` (or something like this), but this index never gets returned. 
This means that, when we get to the `if isnothing(r)` that determines whether we're going to put a phase on a row of the tableau, we've correctly determined that the measurement result is random, but the index of the new stabilizer that needs a phase update is set to `0`, rather than the index of the new stabilizer which is proportional to `pauli`.
This is a little tricky to deal with, since it's not clear that the index of the anticommuting logical will be the same as the index of the new stabilizer that needs its phase set.

**Comment by Krastanov** [comment]
Thanks for reporting this. At its root, it is due to a longstanding question I have had about how to have the API distinguish between "projector is in the stabilizer" and "projector commutes with the stabilizer but is not in it". My original choice was described in detail on the "Datastructure Choice" documentation page and in the `project!` docstring, but they were sufficiently confusing that they led even me to misuse them, causing the bug above in `DenseMeasurement`. Hopefully it is fixed now in https://github.com/Krastanov/QuantumClifford.jl/commit/b86b30e22d398d54198721881b86ae3fd7cb2272 (the changes to the documentation in that commit would explain the rest of the reasoning).

I will make a few more checks, and later today there should be a new release.

**Comment by bcriger** [comment]
Update: at least in Julia 1.6, it looks like the `@test_throws nothing function_that_should_not_throw_exception()` pattern doesn't work properly when the function in question actually doesn't throw an exception, since that's not the same as throwing an exception whose value is `nothing`. If you want to incorporate the MWE as a test, you'll have to add checks to assert that the tableau is correct.

**Comment by Krastanov** [comment]
Yup, those are included in the commit above. You can install it now with `] add QuantumClifford#master` and there should be an actual release shortly.

**Comment by Krastanov** [comment]
This is now available in version 0.4.0
