### ISSUE TITLE
Adding amplitude damping channel in Clifford circuit.

### ISSUE THREAD

**Issue by jisutich** [Krastanov/QuantumClifford.jl#50]
Hi,

I just start learning the use of this package. My attempt is to use Clifford circuit to simulate a quantum circuit with random unitary evolution, projective measurement and amplitude damping. Is it possible to achieve this or at least some approximation of the amplitude damping channel? By the way, if this is not the correct place to ask this kind of question, I apologize for it. (Is there any forum for beginners of this package?)

**Comment by Krastanov** [comment]
Hi, Xiaozhou! This is indeed a good place to ask.

Just to make sure we are on the same page: only Pauli channels and Clifford channels can be simulated with software like this (one that uses the Tabeau formalism). Arbitrary unitary operations and many non-unitary operation (e.g. exact amplitude damping, not some approximation in a Pauli channel) are not something you can simulate in this formalism. Projective measurements can be simulated efficiently with this software if they are of the Z, X, or Y Pauli observables.

Within these constraints, your code might look something like:
```julia
n = 10 # number of qubits
state = one(MixedDestabilizer, n, n) # prepare an initial state

# a few different options to apply a gate, each with different performance characteristics
# a random Clifford operation on all qubits
operation = random_clifford(n)
apply!(state, operation)
# a random Clifford on just three qubits
operation = random_clifford(3)
apply!(state, operation, [2,3,5])
# or a symbolic CNOT gate on qubits 1 and 2
operation = sCNOT(1,2)
apply!(state, operation)
# or a number of other options not enumerated here

# and to perform a projection on a single qubit you can do
projectXrand!(state,4) # measure qubit 4 in the X basis
```

Out of these components you can make a monte carlo simulation. The last function I mentioned is only in the dev branch of the library, which is a bit unstable right now, but should be fixed and out in two weeks. You can install it with `] add QuantumClifford#master`, but the `petrajectories` and `mctrajectories` functions are broken in it right now.

**Comment by jisutich** [comment]
Hi,

Thanks for the reply. Yes, the exact amplitude damping is not available in Clifford circuit. So I am thinking about the reset error mentioned in this [https://qiskit.org/documentation/tutorials/simulators/5_noise_transformation.html](url). Is it possible to realize? Also, I noticed that we can have noisy clifford circuit. What kind of noise do we have? Can they be a good approximation of the amplitude damping? (The reason I want amplitude damping is that our group also want some analytical understanding about the noise, so it will be good if the noise can be close to some well known quantum noise channel). Sorry for so many questions.

**Comment by Krastanov** [comment]
In the form of reset it is fairly doable. It would look like this:

```julia
if rand() < reset_prob
    traceout!(state, [qubit]) # the traceout! function performs a partial trace over the given qubit
else
    result = projectZ!(state, qubit)
    # depending on the value of result, perform a pauli X operation
end
```

This can be nicely packaged in a noisy operation that you just write in a circuit, but this API is exactly the functionality I am significantly revising right now, in the transition to v1.0.0 for this library. In two or three weeks it would probably just be part of the library, but until then there is no "single line of code" way to implement it. You are right that there are noisy clifford circuits supported by this library (the aforementioned mctrajectory and petrajectory functions), but I would advise to not use them until their upcoming redesign is finished.

Help is certainly welcomed in fleshing out this library, which would probably also make this functionality available to you sooner ;)

**Comment by jisutich** [comment]
Hi Stefan:

Thanks for the answer. But I am a little confused about the code above. I guess it is due to my ignorance about both the reset error and clifford circuit. If I do `traceout!`, it will partial trace a qubit and decrease the total number of my qubits, right? My understanding is that the reset error is like acting the Kraus operators on the density operator. And the total number of qubits should not change, right? Is there anything I misunderstand? Also, why should we measure the qubit by `result = projectZ!(state, qubit)`?

**Comment by Krastanov** [comment]
On rereading, there were few misconception:
- You probably know this, but just to make sure we are on the same page, this library (QuantumClifford.jl) does not represent states as density operators and does not represent gates or noise as Kraus operators. This is what permits it to be fast (but also what restricts it to only certain types of "easy" gates).
- The qiskit approximation is taken from here https://arxiv.org/pdf/1207.0046.pdf 
- Think of `traceout!` as destroying the information about the qubit, not the qubit itself (that is a bit too vague... but my point is that you do not end up with fewer qubit). The qubit is still there, but if it was represented by a density matrix, it would have been the identity matrix. The density matrix equivalent of the `traceout!` function is that you performed a partial trace and then you inserted an identity matrix in the place of the missing qubit.
- The general reset channel used as an amplitude decay approximation as defined on that webpage demands that you force the qubit to be in state 0 with some probability p0 or 1 with some (potentially different) probability p1. This requires that you first destroy the state of the qubit and then set it to the given state (0 or 1). So we will need a traceout! followed by a projection.
- Experimentally and in simulation there are a few ways you can do this, revolving around tracing out the qubit and then forcing its state to some new value. The one I wrote above was wrong because I misunderstood the reset channel used in the shared web link (I thought that there were three options: force to 0, force to 1, and simply delete, while only the first two options were used). However, a very similar method is already implemented in this library: `reset_qubit!` https://github.com/Krastanov/QuantumClifford.jl/blob/master/src/project_trace_reset.jl#L631=

You can use it like this:
```
# prepare some random state of 5 qubits in a datastructure that knows how to represent impure states
julia> s = MixedDestabilizer(random_destabilizer(5))
Rank 5 stabilizer
- _Z__Y
+ XZYZ_
- ZZ_XY
- XZ_ZY
+ YYZYX
═══════
- ZY_Z_
- Y_XYY
- Y_YX_
+ _X_XX
- ZXZXX
═══════

# Destroy qubit 5 and place the |0⟩ in its place.
# Notice that even though we replaced the destroyed qubit
# we still have "lost" information, i.e. our state is now impure,
# i.e. it has lower rank, i.e. more entropy.
# This is because the qubit that was destroyed was entangled with some
# other qubits.
julia> reset_qubits!(s, S"Z", 5)
Rank 4 stabilizer
- ZYZXZ
- YYZYZ
- _YZ_Z
- ZXZXX
━━━━━━━
+ XZYZ_
━━━━━━━
- ZY_Z_
- Z_Z__
- Y_YX_
+ ____Z
━━━━━━━
- XXYZZ

# If necessary, apply an X operation to flip the state
julia> apply!(s,sX(5))
Rank 4 stabilizer
+ ZYZXZ
+ YYZYZ
+ _YZ_Z
- ZXZXX
━━━━━━━
+ XZYZ_
━━━━━━━
- ZY_Z_
- Z_Z__
- Y_YX_
- ____Z
━━━━━━━
+ XXYZZ
```

I am happy to meet over videoconf if you would like to discuss this at more length (but it would have to be after the upcoming week).

**Comment by jisutich** [comment]
Thanks. Very clear explanation and they solve my question.
