### ISSUE TITLE
OSX compilation

### ISSUE THREAD

**Issue by BoltzmannEntropy** [Krastanov/QuantumClifford.jl#81]
It seems that Quantiks does not compile because Tectronic does not compile on OSX M1 chip (arm64) 
```

      Info Packages marked with ⌃ and ⌅ have new versions available, but those with ⌅ are restricted by compatibility constraints from upgrading. To see why use `status --outdated -m`
    Building GR → `~/.julia/scratchspaces/44cfe95a-1eb2-52ea-b672-e2afdf69b78f/cf0a9940f250dc3cb6cc6c6821b4bf8a4286cf9c/build.log`
Precompiling project...
  ✗ QuantumClifford
  ✗ QuantumCliffordPlots
  71 dependencies successfully precompiled in 56 seconds. 366 already precompiled. 2 skipped during auto due to previous errors.
  2 dependencies errored. To see a full report either run `import Pkg; Pkg.precompile()` or load the packages
[ Info: Precompiling QuantumClifford [0525e862-1e90-11e9-3e4d-1b39d7109de1]
ERROR: LoadError: Cannot locate artifact 'tectonic_bin' for aarch64-apple-darwin-libgfortran5-cxx11-julia_version+1.8.
```

**Comment by Krastanov** [comment]
Thanks for reporting this!

If you do not need the plotting functionality, you can still use the library. Just `] rm QuantumCliffordPlots` (the one that depends on Quantikz), and keep `QuantumClifford`.

In the meantime I will try to figure out what options there are for Tectonic to run on arm64.

**Comment by Krastanov** [comment]
It seems fixing this mostly depends on the following:

Either fixing these two issues with Tectonic.jl:

- https://github.com/MichaelHatherly/Tectonic.jl/issues/13
- https://github.com/JuliaPackaging/Yggdrasil/issues/5633

Or taking this approach in `Quantikz.jl`

- https://github.com/Krastanov/Quantikz/issues/11

@BoltzmannEntropy , if you have the time to spare, help with the last issue would certainly be appreciated. It should be as simple as `using tectonic_jll` instead of `using Tectonic` and some changes to `Project.toml`, but having it tested by someone with an M1 chip would help a lot.

**Comment by BoltzmannEntropy** [comment]
Sure, I shall give it a try tomorrow. Thanks!

**Comment by Krastanov** [comment]
done in upstream Quantikz.jl
